apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-logs-pvc
  namespace: efk  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Adjust the size as per your needs
  storageClassName: nfs-storageclass # Use your NFS storage class
