apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-logs-pvc
  namespace: efk  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Adjust the size as per your needs
  storageClassName: nfs-storageclass
